# Generated by Django 5.0.6 on 2024-07-04 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vacancy_name', models.CharField(max_length=400)),
                ('area_name', models.CharField(max_length=255)),
                ('salary_from', models.IntegerField()),
                ('salary_to', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('building', models.CharField(default=None, max_length=100)),
                ('raw', models.TextField()),
                ('employer_name', models.CharField(max_length=355)),
                ('requirements', models.TextField()),
                ('responsibilities', models.TextField()),
                ('exp_from', models.IntegerField()),
                ('exp_to', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'db_table': 'vacancies',
            },
        ),
    ]
