# Generated by Django 5.0.6 on 2024-07-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_robot', '0002_remove_vacancy_raw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='exp_from',
            new_name='exper',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='exp_to',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='street',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
