# Generated by Django 5.0.6 on 2024-07-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_robot', '0003_rename_exp_from_vacancy_exper_remove_vacancy_exp_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='exper',
            new_name='exp_from',
        ),
    ]
