# Generated by Django 5.0.6 on 2024-07-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_robot', '0004_rename_exper_vacancy_exp_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='exp_from',
            field=models.CharField(max_length=300),
        ),
    ]
