# Generated by Django 5.0.6 on 2024-07-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_robot', '0007_alter_vacancy_area_name_alter_vacancy_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='created_by',
        ),
    ]
